version: '4.0'
services:
  api:
    build: ./server-side
    container_name: telemeds_contain_new
    ports:
      - "3000:3500"
    volumes:
        - ./server-side:/app
        - /app/node_modules
   