version: '4.0'
services:
  api:
    build: ./server-side
    container_name: telemeds_container
    ports:
      - "3000:3000"
    volumes:
        - ./server-side:/app
        - /app/node_modules
   